### ISSUE TITLE
Need blank lines.

### ISSUE THREAD

**Issue by Amostubal** [Caldfir/RCFC2#1]
Either an option to leave current blank lines in or automatically adding blank lines between I'm guessing we should call them tier 1/definition tokens.

basically the file opening is correct, but as soon as it gets to the definitions, it removes all the spaces between the tokens so like in bodyplans it just shoves the definition of the next right up to the end of the previous one...

leaving the blank line in or maybe asserting a 2 blank line gap between them would allow the files to be better parsed by github, separating the definitions by what they was and what they are changing to in the diff screens... in the current process github just deletes the entire page then presents the entire new page.  rather annoying...  another thing how does this code handles commentary?  I didn't go deep enough to look but some pattern of okay this is a comments, keep these right here behind the token that's here.

Anyways its a really interesting work... I'm going to test it on a raw file that went nuts sometime in the past, and its format is abysmal.

**Comment by Caldfir** [comment]
Glad to hear you found this useful.  Adding an extra separator between definitions seems reasonable - I'll look into it.  

Unfortunately, the way the tool works is by reading all the tags into a little in-memory database, and checking to make sure that each tag can be assigned an appropriate parent.  Because of this, it doesn't really understand "comments" at all in its current form, though I do have some ideas about how they might be detected/handled in the future, so stay tuned :)
